general:
  gpu: 0
  seed: 42
  n_workers: 1
  models_output_dir: ./models/
  output_dir: ./output/
  log_frequency: 10

train:
  criterion: CrossEntropyLoss  # ['CrossEntropyLoss', 'TripletLoss']
  batch_size: 16
  num_epochs: 5
  weight_decay: 0.1
  learning_rate: 1.0e-5  # The initial learning rate for Adam.
  warmup_steps: 500
  adam_epsilon: 1.0e-6  # Epsilon for Adam optimizer.
  max_grad_norm: 1.0  # Max gradient norm.
  gradient_accumulation_steps: 1  # Number of updates steps to accumulate before performing a backward/update pass
  eval_frequency: 500
  eval_batch_size: 32
  triplet_margin: 7.5

model:
  name: bert-base-cased  # ['intfloat/e5-base-v2', 'bert-base-cased', 'DeepPavlov/rubert-base-cased']
  relation_embedding_size: 768
  dropout_rate: 0.1

dataset:
  path: ./datasets/prepared/WebNLG/
  max_len: 300
  use_predefined_split: True
  use_zero_shot_split: False
